name: Evercode checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download test file
        run: curl -0 https://devpass-api-bucket.s3.amazonaws.com/testes/HelloEvercodeTests.swift -o Tests/HelloEvercodeTests/HelloEvercodeTests.swift

      - name: Evercode checks
        run: swift build && swift test